---
- name: run cleanup script
  command: /usr/local/sbin/gentoo_system_cleanup.zsh

- name: disable setuid
  command: find / \( -path /proc -o -path /dev -o -path /sys \) -prune -o -not -type d -perm /a+s -exec chmod a-s {} +


# vim: set sw=2 ts=2 sts=2 expandtab:
